[project]
name = "rdtbkmkchk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "loguru>=0.7.2",
    "praw>=7.7.1",
    "python-dotenv>=1.0.1",
]
